# -*- coding: utf-8 -*-
"""pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z0HT3ncpLuOzDtuahPNIV4tQon5O1K6C
"""

import warnings
warnings.filterwarnings("ignore")

import os
import json
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_validate
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    classification_report, confusion_matrix, roc_auc_score,
    roc_curve, precision_recall_curve, average_precision_score,
    f1_score, matthews_corrcoef
)
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer

from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline

import xgboost as xgb
import pickle

RAW_DATA  = "/mnt/user-data/uploads/WA_Fn-UseC_-Telco-Customer-Churn.csv"
OUT_DIR   = "/mnt/user-data/outputs"
os.makedirs(OUT_DIR, exist_ok=True)

df = pd.read_csv("/content/WA_Fn-UseC_-Telco-Customer-Churn.csv")
print(f"Raw shape : {df.shape}")
print(f"Churn dist:\n{df['Churn'].value_counts(normalize=True).round(3)}")

df.drop(columns=["customerID"], inplace=True)

# TotalCharges is object — coerce, fill NaN with median
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
n_missing = df["TotalCharges"].isna().sum()
print(f"TotalCharges NaN after coerce: {n_missing}")
df["TotalCharges"].fillna(df["TotalCharges"].median(), inplace=True)

# Binary encode target
df["Churn"] = (df["Churn"] == "Yes").astype(int)

print(f"Cleaned shape: {df.shape}")

df["AvgMonthlySpend"]   = df["TotalCharges"] / (df["tenure"] + 1)
df["TenureGroup"]       = pd.cut(df["tenure"],
                                  bins=[0, 12, 24, 48, 72],
                                  labels=["0-1yr", "1-2yr", "2-4yr", "4-6yr"],
                                  include_lowest=True)

# Count number of add-on services subscribed
addon_cols = ["OnlineSecurity", "OnlineBackup", "DeviceProtection",
              "TechSupport", "StreamingTV", "StreamingMovies"]
df["NumAddOns"] = df[addon_cols].apply(
    lambda row: sum(v == "Yes" for v in row), axis=1
)

# Flag high-value, high-risk customers
df["HighValueAtRisk"] = (
    (df["MonthlyCharges"] > df["MonthlyCharges"].quantile(0.75)) &
    (df["Contract"] == "Month-to-month")
).astype(int)

print("New features: AvgMonthlySpend, TenureGroup, NumAddOns, HighValueAtRisk")

TARGET = "Churn"
X = df.drop(columns=[TARGET])
y = df[TARGET]

# Identify column types
num_cols = X.select_dtypes(include=["int64", "float64"]).columns.tolist()
cat_cols = X.select_dtypes(include=["object", "category"]).columns.tolist()
print(f"Numerical   : {num_cols}")
print(f"Categorical : {cat_cols}")

# Preprocessor — with imputers to handle any NaN before SMOTE
num_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler",  StandardScaler()),
])
cat_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("ohe",     OneHotEncoder(handle_unknown="ignore", drop="first")),
])

preprocessor = ColumnTransformer(transformers=[
    ("num", num_transformer, num_cols),
    ("cat", cat_transformer, cat_cols),
])
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
print(f"Train: {X_train.shape[0]} | Test: {X_test.shape[0]}")
print(f"Train churn rate: {y_train.mean():.3f}")
print(f"Test  churn rate: {y_test.mean():.3f}")

# Class imbalance ratio (for XGBoost scale_pos_weight)
neg, pos = (y_train == 0).sum(), (y_train == 1).sum()
spw = neg / pos          # ~2.8
print(f"scale_pos_weight for XGBoost: {spw:.2f}")

smote = SMOTE(random_state=42, k_neighbors=5)

# ── (A) Logistic Regression ──────────────────────────────
lr_pipeline = ImbPipeline(steps=[
    ("preprocessor", preprocessor),
    ("smote",        smote),
    ("clf",          LogisticRegression(
                         class_weight="balanced",
                         max_iter=1000,
                         C=0.1,
                         solver="lbfgs",
                         random_state=42))
])

# ── (B) Random Forest ────────────────────────────────────
rf_pipeline = ImbPipeline(steps=[
    ("preprocessor", preprocessor),
    ("smote",        smote),
    ("clf",          RandomForestClassifier(
                         n_estimators=300,
                         max_depth=None,
                         class_weight="balanced",
                         min_samples_leaf=5,
                         random_state=42,
                         n_jobs=-1))
])

# ── (C) XGBoost ──────────────────────────────────────────
xgb_pipeline = ImbPipeline(steps=[
    ("preprocessor", preprocessor),
    ("smote",        smote),
    ("clf",          xgb.XGBClassifier(
                         n_estimators=300,
                         learning_rate=0.05,
                         max_depth=5,
                         scale_pos_weight=spw,   # imbalance weight
                         subsample=0.8,
                         colsample_bytree=0.8,
                         eval_metric="logloss",
                         random_state=42,
                         use_label_encoder=False))
])

MODELS = {
    "Logistic Regression": lr_pipeline,
    "Random Forest":       rf_pipeline,
    "XGBoost":             xgb_pipeline,
}

# ── Train & CV score ─────────────────────────────────────
cv      = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
results = {}

for name, pipe in MODELS.items():
    print(f"\n  ▶ {name}")
    cv_res = cross_validate(
        pipe, X_train, y_train, cv=cv,
        scoring=["roc_auc", "f1", "average_precision"],
        return_train_score=False, n_jobs=-1
    )
    print(f"    CV ROC-AUC : {cv_res['test_roc_auc'].mean():.4f} ± {cv_res['test_roc_auc'].std():.4f}")
    print(f"    CV F1      : {cv_res['test_f1'].mean():.4f} ± {cv_res['test_f1'].std():.4f}")
    print(f"    CV Avg-Prec: {cv_res['test_average_precision'].mean():.4f}")

    pipe.fit(X_train, y_train)
    results[name] = {"cv": cv_res, "pipe": pipe}

metrics_records = []

for name, res in results.items():
    pipe   = res["pipe"]
    y_pred = pipe.predict(X_test)
    y_prob = pipe.predict_proba(X_test)[:, 1]

    auc  = roc_auc_score(y_test, y_prob)
    ap   = average_precision_score(y_test, y_prob)
    f1   = f1_score(y_test, y_pred)
    mcc  = matthews_corrcoef(y_test, y_pred)

    print(f"\n  ── {name} ──")
    print(f"  ROC-AUC  : {auc:.4f}")
    print(f"  Avg-Prec : {ap:.4f}")
    print(f"  F1       : {f1:.4f}")
    print(f"  MCC      : {mcc:.4f}")
    print(classification_report(y_test, y_pred, target_names=["Stay", "Churn"]))

    metrics_records.append({
        "Model": name, "ROC_AUC": round(auc, 4),
        "Avg_Precision": round(ap, 4), "F1": round(f1, 4), "MCC": round(mcc, 4),
        "y_prob": y_prob, "y_pred": y_pred,
    })

# ── Identify best model ───────────────────────────────────
best = max(metrics_records, key=lambda x: x["ROC_AUC"])
print(f"\n  ★  Best model: {best['Model']}  (ROC-AUC = {best['ROC_AUC']})")

print("\n  Generating plots …")

PALETTE = ["#4C72B0", "#DD8452", "#55A868"]

# ── 1. ROC curves ─────────────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle("Model Comparison — ROC & PR Curves", fontsize=14, fontweight="bold")

for ax, rec, col in zip(axes, metrics_records, PALETTE):
    fpr, tpr, _ = roc_curve(y_test, rec["y_prob"])
    ax.plot(fpr, tpr, color=col, lw=2,
            label=f"ROC-AUC = {rec['ROC_AUC']:.4f}")
    ax.plot([0,1],[0,1],"k--", lw=1)
    ax.set_title(rec["Model"], fontweight="bold")
    ax.set_xlabel("False Positive Rate")
    ax.set_ylabel("True Positive Rate")
    ax.legend(loc="lower right")
    ax.grid(alpha=0.3)

plt.tight_layout()
plt.savefig(f"{OUT_DIR}/01_roc_curves.png", dpi=150, bbox_inches="tight")
plt.close()

# ── 2. Confusion matrices ─────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle("Confusion Matrices (Hold-Out)", fontsize=14, fontweight="bold")

for ax, rec, col in zip(axes, metrics_records, PALETTE):
    cm = confusion_matrix(y_test, rec["y_pred"])
    sns.heatmap(cm, annot=True, fmt="d", ax=ax,
                cmap="Blues", cbar=False,
                xticklabels=["Stay","Churn"],
                yticklabels=["Stay","Churn"])
    ax.set_title(rec["Model"], fontweight="bold")
    ax.set_ylabel("Actual"); ax.set_xlabel("Predicted")

plt.tight_layout()
plt.savefig(f"{OUT_DIR}/02_confusion_matrices.png", dpi=150, bbox_inches="tight")
plt.close()

# ── 3. Precision-Recall curves ────────────────────────────
fig, ax = plt.subplots(figsize=(8, 6))
for rec, col in zip(metrics_records, PALETTE):
    prec, rec_vals, _ = precision_recall_curve(y_test, rec["y_prob"])
    ax.plot(rec_vals, prec, color=col, lw=2, label=f"{rec['Model']} (AP={rec['Avg_Precision']:.4f})")

ax.set_xlabel("Recall"); ax.set_ylabel("Precision")
ax.set_title("Precision-Recall Curves", fontweight="bold")
ax.legend(); ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig(f"{OUT_DIR}/03_pr_curves.png", dpi=150, bbox_inches="tight")
plt.close()

# ── 4. Metric comparison bar chart ────────────────────────
metrics_df = pd.DataFrame([
    {"Model": r["Model"], "ROC-AUC": r["ROC_AUC"],
     "Avg-Precision": r["Avg_Precision"], "F1": r["F1"], "MCC": r["MCC"]}
    for r in metrics_records
]).set_index("Model")

fig, ax = plt.subplots(figsize=(10, 5))
metrics_df.plot(kind="bar", ax=ax, colormap="tab10", edgecolor="white", width=0.7)
ax.set_title("Model Performance Comparison", fontweight="bold", fontsize=13)
ax.set_ylabel("Score"); ax.set_xticklabels(ax.get_xticklabels(), rotation=15)
ax.legend(loc="lower right"); ax.set_ylim(0, 1.05); ax.grid(axis="y", alpha=0.3)
plt.tight_layout()
plt.savefig(f"{OUT_DIR}/04_metrics_comparison.png", dpi=150, bbox_inches="tight")
plt.close()

# ── 5. Feature Importance (best model = XGBoost typically) ─
best_pipe  = results[best["Model"]]["pipe"]
clf        = best_pipe.named_steps["clf"]
pre        = best_pipe.named_steps["preprocessor"]

try:
    ohe_names  = pre.named_transformers_["cat"].get_feature_names_out(cat_cols).tolist()
    all_feats  = num_cols + ohe_names

    if hasattr(clf, "feature_importances_"):
        importances = clf.feature_importances_
    else:
        importances = np.abs(clf.coef_[0])

    feat_df = (pd.DataFrame({"Feature": all_feats, "Importance": importances})
                 .sort_values("Importance", ascending=False).head(20))

    fig, ax = plt.subplots(figsize=(9, 7))
    sns.barplot(data=feat_df, y="Feature", x="Importance", palette="Blues_r", ax=ax)
    ax.set_title(f"Top-20 Feature Importances — {best['Model']}", fontweight="bold")
    ax.set_xlabel("Importance"); ax.grid(axis="x", alpha=0.3)
    plt.tight_layout()
    plt.savefig(f"{OUT_DIR}/05_feature_importance.png", dpi=150, bbox_inches="tight")
    plt.close()
    print("  Feature importance plot saved.")
except Exception as e:
    print(f"  Feature importance skipped: {e}")

# ── 6. Churn probability distribution ─────────────────────
best_probs = best["y_prob"]
fig, ax = plt.subplots(figsize=(9, 5))
ax.hist(best_probs[y_test == 0], bins=40, alpha=0.6, color="#4C72B0", label="Stay")
ax.hist(best_probs[y_test == 1], bins=40, alpha=0.6, color="#DD8452", label="Churn")
ax.axvline(0.5, color="red", linestyle="--", lw=1.5, label="Default threshold 0.5")
ax.set_xlabel("Predicted Churn Probability"); ax.set_ylabel("Count")
ax.set_title(f"Predicted Probability Distribution — {best['Model']}", fontweight="bold")
ax.legend(); ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig(f"{OUT_DIR}/06_prob_distribution.png", dpi=150, bbox_inches="tight")
plt.close()

# ── Save best model + metrics ──────────────────────────────
model_path   = f"{OUT_DIR}/best_model.pkl"
metrics_path = f"{OUT_DIR}/metrics_summary.json"

with open(model_path, "wb") as f:
    pickle.dump(best_pipe, f)

summary = {r["Model"]: {k: v for k, v in r.items() if k not in ("y_prob","y_pred")}
           for r in metrics_records}
with open(metrics_path, "w") as f:
    json.dump(summary, f, indent=2)

print(f"\n  Model saved → {model_path}")
print(f"  Metrics   → {metrics_path}")
print("\n" + "═"*60)
print("  PIPELINE COMPLETE ✓")
print("═"*60)

from google.colab import drive
drive.mount('/content/drive')